# Generated by Django 3.2 on 2021-04-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='solana_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
