# Generated by Django 3.2 on 2021-04-27 01:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_solana_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catastro_id', models.CharField(max_length=100, unique=True)),
                ('solana_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='identification',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ref_collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
