# Generated by Django 3.2 on 2021-04-27 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_delete_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.JSONField(blank=True, null=True)),
                ('identification', models.JSONField(blank=True, null=True)),
                ('name', models.JSONField(blank=True, null=True)),
                ('property', models.JSONField(blank=True, null=True)),
                ('quality', models.JSONField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('city', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to='property.contributor'),
        ),
    ]
