# Generated by Django 3.2 on 2021-04-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210427_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='form_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
